const PostActionTypes = {
    FETCH_ALL_POSTS_START: 'FETCH_ALL_POSTS_START',
    FETCH_ALL_POSTS_SUCCESS: 'FETCH_ALL_POSTS_SUCCESS',
    FETCH_ALL_POSTS_FAILURE: 'FETCH_ALL_POSTS_FAILURE',
    UPDATE_POST_START: 'UPDATE_POST_START',
    UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
    UPDATE_POST_FAILURE: 'UPDATE_POST_FAILURE',
    CREATE_POST_START: 'CREATE_POST_START',
    CREATE_POST_SUCCESS: 'CREATE_POST_SUCCESS',
    CREATE_POST_FAILURE: 'CREATE_POST_FAILURE',
    DELETE_POST_START: 'DELETE_POST_START',
    DELETE_POST_SUCCESS: 'DELETE_POST_SUCCESS',
    DELETE_POST_FAILURE: 'DELETE_POST_FAILURE'
}

export default PostActionTypes;
